[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fanuc-rmi"
version = "0.1.5"
description = "Simple FANUC RMI client"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["ikpy"]

[tool.setuptools]
packages = ["fanuc_rmi"]
