[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fanuc-rmi"
version = "0.1.4"
description = "Simple FANUC RMI client"
readme = "README.md"
requires-python = ">=3.11"

[tool.setuptools]
packages = ["fanuc_rmi"]
